name: Validate Conventional Commit Title
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-title-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf refactor revert style test bump release
